name: Hello World CI
on:
  push:
    branches:
      - main
jobs:
  ScriptRunJob:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Execute Python script
        run: python test.py
      - name: Execute Shell script
        run: bash test.sh
